# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# ZSH_THEME="juanghurtado"
ZSH_THEME="powerlevel10k/powerlevel10k"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

if [ -f /usr/local/bin/scw-metadata ]; then
    plugins=(git docker zsh-syntax-highlighting ubuntu thulio)
else
    plugins=(git docker zsh-syntax-highlighting brew thulio)
fi

source $ZSH/oh-my-zsh.sh

#autoload -Uz compinit
#compinit
#compinit -C
#if [[ -f /usr/local/bin/gdate ]]; then
#    if [ $(/usr/local/bin/gdate -d @$(/usr/local/bin/gstat -c%Y ${HOME}/.zcompdump) +"%Y%m%d") != $(/usr/local/bin/gdate +"%Y%m%d") ]; then
#      compinit
#    else
#      compinit -C
#    fi
#else
#    if [ $(date -d @$(stat -c%Y ${HOME}/.zcompdump) +"%Y%m%d") != $(date +"%Y%m%d") ]; then
#      compinit
#    else
#      compinit -C
#    fi
#fi

export EDITOR='nvim'
export PATH=/usr/local/bin:$PATH:$JAVA_HOME/bin:/usr/bin/vendor_perl:$HOME/bin
export GOPATH=$HOME/go
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1
export WORKON_HOME=~/.virtualenvs/

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.


if [[ -d "${HOME}/.asdf" ]]; then
    . $HOME/.asdf/asdf.sh
    . $HOME/.asdf/completions/asdf.bash
fi

if [[ -f /usr/local/etc/profile.d/z.sh ]]; then
      . /usr/local/etc/profile.d/z.sh
fi

if [[ -f ${HOME}/.poetry/env ]]; then
    source $HOME/.poetry/env
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
